# TODO: can push readlie into next detmonad image

FROM parfunc/detmonad:image-0.1

# RUN apt-get install -y mothur

RUN apt-get update -y && apt-get install -y libreadline6
# libreadline-dev
# lib64readline-dev
# libreadline7
# libreadline-dev
# lib64readline6
